version: '3.8'

services:
  mysqldb:
    image: "mysql:latest"
    container_name: where2-mysql-db
    environment:
      MYSQL_DATABASE: where2
      MYSQL_USER: user
      MYSQL_PASSWORD: my_Strong_Password
      MYSQL_ROOT_PASSWORD: my_Strong_Password
    ports:
      - "3307:3306"
    restart: always

  server:
    build: .
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - mysqldb